### ISSUE TITLE
Change experimentalGameClass branch to something else

### ISSUE THREAD

**Issue by James0199** [James0199/TextopolyAgain#8]
I'm thinking of changing #5 (experimentalGameClass) to Patel or something or even make a fork instead of a branch
Make sure to change the branch name in your workstation or else: return
(Finally, a real issue lol)

**Comment by patelheet30** [comment]
No. Please leave everything the way it is because I have my IDE perfectly setup now 😭

**Comment by James0199** [comment]
shid

**Comment by James0199** [comment]
change to a fork!

**Comment by patelheet30** [comment]
Changed to a fork and will delete the brnanch
